### ISSUE TITLE
Alter check version action to better mirror behavior under `setup.py`

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us-data#51]
Doesn't seem like there's an obvious solution, but after adding the versioning commit, the check version action fails every time, meaning we can't get all-tick PRs.

**Comment by anth-volk** [comment]
Here's the problem: The script to generate the changelog consumes the changelog_entry.yaml file, such that on subsequent action runs, it's missing and no longer possible to generate the log. This is because, unlike `setup.py`, `pyproject.toml` provides no method of quickly and easily pulling the version number. We'll have to determine a way to easily pull the version without installing the package and/or installing a TOML parser.

**Comment by MaxGhenis** [comment]
Would it help to go back to setup.py for the time being?

**Comment by anth-volk** [comment]
Nikhil implemented a workaround for the time being. I think the best thing would be to see if there is a way we can get versioning working, since: 

1. We're going to have to shift everything to `pyproject.toml` in the future, anyway, as `setup.py` has become increasingly deprecated. Starting with pip v25, we won't even be able to install editable without extra configuration, if I'm reading the deprecation warnings correctly
2. Doing so would help inform an existing PR open on `core` to shift to `pyproject.toml`
3. It appears to be the only thing we haven't gotten fully configured when shifting over to `pyproject.toml`, and I think it'd be a shame to throw out the other 90%

**Comment by anth-volk** [comment]
That said, I don't think we should move anything else over until this is fixed

**Comment by nikhilwoodruff** [comment]
Well why don't we just force users to run `make changeling` in PRs themselves in the time being- seems OK to me.
